# Generated by Django 4.1.7 on 2023-04-07 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Убедитесь, что это значение больше либо равно 1.'), django.core.validators.MaxValueValidator(32767, message='Убедитесь, что это значение меньше либо равно 32767.')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Убедитесь, что это значение больше либо равно 1.'), django.core.validators.MaxValueValidator(32767, message='Убедитесь, что это значение меньше либо равно 32767.')], verbose_name='Количество'),
        ),
    ]
